rules:
  port_scan:
    window_sec: 5
    threshold_ports: 12
    cooldown_sec: 15


  dns_spike:
    window_seconds: 10
    query_threshold: 3
    min_window_packets: 3
    _cooldown_seconds: 5
    unique_dst_threshold: 0
    ignore_local: true
    ignore_src_prefixes: ["127."]
    ignore_dst_ips: ["127.0.0.53"]

